### ISSUE TITLE
getting python error on run

### ISSUE THREAD

**Issue by ashmirza** [cado-security/cloudgrep#31]
getting the following error when I run cloudgrep

```
Traceback (most recent call last):
  File "/home/ec2-user/cloudgrep/cloudgrep.py", line 1, in <module>
    from cloudgrep import __main__
  File "/home/ec2-user/cloudgrep/cloudgrep/__main__.py", line 6, in <module>
    from cloudgrep.cloudgrep import CloudGrep
  File "/home/ec2-user/cloudgrep/cloudgrep/cloudgrep.py", line 46
    match log_type:
          ^
SyntaxError: invalid syntax
```

I can't figure out why this is, an older version of the package installed works fine.

**Comment by chrisdoman** [comment]
Hi @ashmirza I deployed an Amazon linux instance, and looks like you just need to upgrade to python 3.10 or later.

**Comment by chrisdoman** [comment]
Fix looks good, thanks for raising
